### ISSUE TITLE
Multiple logger files per row

### ISSUE THREAD

**Issue by nicokant** [NINAnor/seabird-gps-database#19]
When multiple logger files have the same metadata how should we proceed?
1. Separator - allow to provide all the filenames using a separator in the column
2. Zip file - allow to upload zipfiles and extract&parse all the files in it

**Comment by ninadehnhard** [comment]
I just send an email about this one. In the long-term, definately zip-file! As we have undone the zip-files for the tdrs due to the misunderstanding, it would be great if you could make a temporary exception so that we can specify multiple files for the tdr-files, where they were already specified. But for the future, I think the best solution is indeed to have zip-files for both tdr & gls logger files, yes. Would that work for you?

**Comment by nicokant** [comment]
Yes, I can do that. TDR file names can be separated by `;`.

Implemented in b05817e85da2e36bc446d0e5c2e7ed1a4da238b2
